### ISSUE TITLE
Example not working (anymore?)

### ISSUE THREAD

**Issue by bcambel** [mjsax/flink-external#1]
Hi, 

When running the example, I am getting the following exception

```
12/10/2015 00:45:03	CHAIN DataSource (at invoke0(NativeMethodAccessorImpl.java:-2) (org.apache.flink.api.java.io.CollectionInputFormat)) -> FlatMap (FlatMap at invoke0(NativeMethodAccessorImpl.java:-2)) -> Combine(SUM(1), at invoke0(NativeMethodAccessorImpl.java:-2)(1/1) switched to SCHEDULED 
12/10/2015 00:45:03	CHAIN DataSource (at invoke0(NativeMethodAccessorImpl.java:-2) (org.apache.flink.api.java.io.CollectionInputFormat)) -> FlatMap (FlatMap at invoke0(NativeMethodAccessorImpl.java:-2)) -> Combine(SUM(1), at invoke0(NativeMethodAccessorImpl.java:-2)(1/1) switched to DEPLOYING 
12/10/2015 00:45:04	CHAIN DataSource (at invoke0(NativeMethodAccessorImpl.java:-2) (org.apache.flink.api.java.io.CollectionInputFormat)) -> FlatMap (FlatMap at invoke0(NativeMethodAccessorImpl.java:-2)) -> Combine(SUM(1), at invoke0(NativeMethodAccessorImpl.java:-2)(1/1) switched to FAILED 
java.lang.Exception: Call to registerInputOutput() of invokable failed
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:529)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: The initialization of the DataSource's outputs caused an error: Could not read the user code wrapper: flinker.core.tokenizer
	at org.apache.flink.runtime.operators.DataSourceTask.registerInputOutput(DataSourceTask.java:89)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:526)
	... 1 more
Caused by: org.apache.flink.runtime.operators.util.CorruptConfigurationException: Could not read the user code wrapper: flinker.core.tokenizer
	at org.apache.flink.runtime.operators.util.TaskConfig.getStubWrapper(TaskConfig.java:284)
	at org.apache.flink.runtime.operators.BatchTask.instantiateUserCode(BatchTask.java:1465)
	at org.apache.flink.runtime.operators.chaining.ChainedFlatMapDriver.setup(ChainedFlatMapDriver.java:39)
	at org.apache.flink.runtime.operators.chaining.ChainedDriver.setup(ChainedDriver.java:78)
	at org.apache.flink.runtime.operators.BatchTask.initOutputs(BatchTask.java:1336)
	at org.apache.flink.runtime.operators.DataSourceTask.initOutputs(DataSourceTask.java:284)
	at org.apache.flink.runtime.operators.DataSourceTask.registerInputOutput(DataSourceTask.java:86)
	... 2 more
Caused by: java.lang.ClassNotFoundException: flinker.core.tokenizer
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:278)
	at org.apache.flink.util.InstantiationUtil$ClassLoaderObjectInputStream.resolveClass(InstantiationUtil.java:71)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1612)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1517)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1771)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1997)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1921)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at org.apache.flink.util.InstantiationUtil.deserializeObject(InstantiationUtil.java:294)
	at org.apache.flink.util.InstantiationUtil.readObjectFromConfig(InstantiationUtil.java:255)
	at org.apache.flink.runtime.operators.util.TaskConfig.getStubWrapper(TaskConfig.java:282)
	... 8 more

12/10/2015 00:45:04	Job execution switched to status FAILING.
12/10/2015 00:45:04	CHAIN Reduce (SUM(1), at invoke0(NativeMethodAccessorImpl.java:-2) -> FlatMap (collect())(1/4) switched to CANCELED 
12/10/2015 00:45:04	CHAIN Reduce (SUM(1), at invoke0(NativeMethodAccessorImpl.java:-2) -> FlatMap (collect())(2/4) switched to CANCELED 
12/10/2015 00:45:04	CHAIN Reduce (SUM(1), at invoke0(NativeMethodAccessorImpl.java:-2) -> FlatMap (collect())(3/4) switched to CANCELED 
12/10/2015 00:45:04	CHAIN Reduce (SUM(1), at invoke0(NativeMethodAccessorImpl.java:-2) -> FlatMap (collect())(4/4) switched to CANCELED 
12/10/2015 00:45:04	DataSink (collect() sink)(1/4) switched to CANCELED 
12/10/2015 00:45:04	DataSink (collect() sink)(2/4) switched to CANCELED 
12/10/2015 00:45:04	DataSink (collect() sink)(3/4) switched to CANCELED 
12/10/2015 00:45:04	DataSink (collect() sink)(4/4) switched to CANCELED 
12/10/2015 00:45:04	Job execution switched to status FAILED.
Exception in thread "main" org.apache.flink.runtime.client.JobExecutionException: Job execution failed., compiling:(/tmp/form-init8957215900997627965.clj:1:73)
	at clojure.lang.Compiler.load(Compiler.java:7239)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: org.apache.flink.runtime.client.JobExecutionException: Job execution failed.
	at org.apache.flink.runtime.jobmanager.JobManager$$anonfun$handleMessage$1$$anonfun$applyOrElse$5.apply$mcV$sp(JobManager.scala:563)
	at org.apache.flink.runtime.jobmanager.JobManager$$anonfun$handleMessage$1$$anonfun$applyOrElse$5.apply(JobManager.scala:509)
	at org.apache.flink.runtime.jobmanager.JobManager$$anonfun$handleMessage$1$$anonfun$applyOrElse$5.apply(JobManager.scala:509)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:401)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.Exception: Call to registerInputOutput() of invokable failed
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:529)

```

Thanks

**Comment by mjsax** [comment]
How do you execute the code? It works for me inside Intellij.

**Comment by bcambel** [comment]
by doing lein run. Apache Flink 0.10.1 as the project dependency.

On Thu, Dec 10, 2015 at 1:37 PM, Matthias J. Sax <notifications@github.com>
wrote:

> How do you execute the code? It works for me inside Intellij.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mjsax/flink-external/issues/1#issuecomment-163598210>.
>



-- 
Regards ,
Bahadir Cambel

**Comment by mjsax** [comment]
I just updated this including `project.clj` file. This works for me. Please try it out.

**Comment by bcambel** [comment]
the path of the WordCount is not correct. 
```

**Comment by mjsax** [comment]
I started this a an maven project. So this is maven structure. And it works for me... strange (but I am somewhat new to Clojure and lein).

```
flink-clojure$ lein run
log4j:WARN No appenders could be found for logger (org.apache.flink.api.java.ExecutionEnvironment).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
12/10/2015 15:00:51     Job execution switched to status RUNNING.
12/10/2015 15:00:51     CHAIN DataSource (at invoke0(NativeMethodAccessorImpl.java:-2) (org.apache.flink.api.java.io.CollectionInputFormat)) -> FlatMap (FlatMap at invoke0(NativeMethodAccessorImpl.java:-2)) -> Combine(SUM(1), at invoke0(NativeMethodAccessorImpl.java:-2)(1/1) switched to SCHEDULED 
12/10/2015 15:00:51     CHAIN DataSource (at invoke0(NativeMethodAccessorImpl.java:-2) (org.apache.flink.api.java.io.CollectionInputFormat)) -> FlatMap (FlatMap at invoke0(NativeMethodAccessorImpl.java:-2)) -> Combine(SUM(1), at invoke0(NativeMethodAccessorImpl.java:-2)(1/1) switched to DEPLOYING 
12/10/2015 15:00:51     CHAIN DataSource (at invoke0(NativeMethodAccessorImpl.java:-2) (org.apache.flink.api.java.io.CollectionInputFormat)) -> FlatMap (FlatMap at invoke0(NativeMethodAccessorImpl.java:-2)) -> Combine(SUM(1), at invoke0(NativeMethodAccessorImpl.java:-2)(1/1) switched to RUNNING 
12/10/2015 15:00:51     CHAIN Reduce (SUM(1), at invoke0(NativeMethodAccessorImpl.java:-2) -> FlatMap (collect())(2/4) switched to SCHEDULED 
12/10/2015 15:00:51     CHAIN Reduce (SUM(1), at invoke0(NativeMethodAccessorImpl.java:-2) -> FlatMap (collect())(1/4) switched to SCHEDULED 
12/10/2015 15:00:51     CHAIN Reduce (SUM(1), at invoke0(NativeMethodAccessorImpl.java:-2) -> FlatMap (collect())(3/4) switched to SCHEDULED 
12/10/2015 15:00:51     CHAIN Reduce (SUM(1), at invoke0(NativeMethodAccessorImpl.java:-2) -> FlatMap (collect())(1/4) switched to DEPLOYING 
12/10/2015 15:00:51     CHAIN Reduce (SUM(1), at invoke0(NativeMethodAccessorImpl.java:-2) -> FlatMap (collect())(3/4) switched to DEPLOYING 
12/10/2015 15:00:51     CHAIN Reduce (SUM(1), at invoke0(NativeMethodAccessorImpl.java:-2) -> FlatMap (collect())(2/4) switched to DEPLOYING 
12/10/2015 15:00:51     CHAIN Reduce (SUM(1), at invoke0(NativeMethodAccessorImpl.java:-2) -> FlatMap (collect())(4/4) switched to SCHEDULED 
12/10/2015 15:00:51     CHAIN Reduce (SUM(1), at invoke0(NativeMethodAccessorImpl.java:-2) -> FlatMap (collect())(4/4) switched to DEPLOYING 
12/10/2015 15:00:51     CHAIN DataSource (at invoke0(NativeMethodAccessorImpl.java:-2) (org.apache.flink.api.java.io.CollectionInputFormat)) -> FlatMap (FlatMap at invoke0(NativeMethodAccessorImpl.java:-2)) -> Combine(SUM(1), at invoke0(NativeMethodAccessorImpl.java:-2)(1/1) switched to FINISHED 
12/10/2015 15:00:51     CHAIN Reduce (SUM(1), at invoke0(NativeMethodAccessorImpl.java:-2) -> FlatMap (collect())(3/4) switched to RUNNING 
12/10/2015 15:00:51     CHAIN Reduce (SUM(1), at invoke0(NativeMethodAccessorImpl.java:-2) -> FlatMap (collect())(4/4) switched to RUNNING 
12/10/2015 15:00:51     CHAIN Reduce (SUM(1), at invoke0(NativeMethodAccessorImpl.java:-2) -> FlatMap (collect())(1/4) switched to RUNNING 
12/10/2015 15:00:51     CHAIN Reduce (SUM(1), at invoke0(NativeMethodAccessorImpl.java:-2) -> FlatMap (collect())(2/4) switched to RUNNING 
12/10/2015 15:00:51     DataSink (collect() sink)(4/4) switched to SCHEDULED 
12/10/2015 15:00:51     DataSink (collect() sink)(4/4) switched to DEPLOYING 
12/10/2015 15:00:51     DataSink (collect() sink)(1/4) switched to SCHEDULED 
12/10/2015 15:00:51     DataSink (collect() sink)(1/4) switched to DEPLOYING 
12/10/2015 15:00:51     DataSink (collect() sink)(2/4) switched to SCHEDULED 
12/10/2015 15:00:51     DataSink (collect() sink)(2/4) switched to DEPLOYING 
12/10/2015 15:00:51     DataSink (collect() sink)(3/4) switched to SCHEDULED 
12/10/2015 15:00:51     DataSink (collect() sink)(3/4) switched to DEPLOYING 
12/10/2015 15:00:51     CHAIN Reduce (SUM(1), at invoke0(NativeMethodAccessorImpl.java:-2) -> FlatMap (collect())(4/4) switched to FINISHED 
12/10/2015 15:00:51     CHAIN Reduce (SUM(1), at invoke0(NativeMethodAccessorImpl.java:-2) -> FlatMap (collect())(1/4) switched to FINISHED 
12/10/2015 15:00:51     DataSink (collect() sink)(4/4) switched to RUNNING 
12/10/2015 15:00:51     DataSink (collect() sink)(1/4) switched to RUNNING 
12/10/2015 15:00:51     CHAIN Reduce (SUM(1), at invoke0(NativeMethodAccessorImpl.java:-2) -> FlatMap (collect())(3/4) switched to FINISHED 
12/10/2015 15:00:51     CHAIN Reduce (SUM(1), at invoke0(NativeMethodAccessorImpl.java:-2) -> FlatMap (collect())(2/4) switched to FINISHED 
12/10/2015 15:00:51     DataSink (collect() sink)(4/4) switched to FINISHED 
12/10/2015 15:00:51     DataSink (collect() sink)(1/4) switched to FINISHED 
12/10/2015 15:00:51     DataSink (collect() sink)(2/4) switched to RUNNING 
12/10/2015 15:00:51     DataSink (collect() sink)(3/4) switched to RUNNING 
12/10/2015 15:00:51     DataSink (collect() sink)(2/4) switched to FINISHED 
12/10/2015 15:00:51     DataSink (collect() sink)(3/4) switched to FINISHED 
12/10/2015 15:00:51     Job execution switched to status FINISHED.
(and,1)
(me,2)
(please,1)
(test,1)
(too,1)
```

**Comment by mjsax** [comment]
After a `mvn clean` I get the same error as you... Maven and lein conflict... Will fix it.

**Comment by bcambel** [comment]
thanks

**Comment by mjsax** [comment]
Just updated again. See README file.

Are you running on Linux? I added a symbolic link in `flink-clojure/src`: `src -> main/clojure`. This bridges the gap between Maven and Clojure.

**Comment by bcambel** [comment]
interestingly doing a ```lein compile``` before ```lein run``` solves the problem. Once you do a ```lein clean```, then you must do ```lein compile```.

**Comment by bcambel** [comment]
I can also confirm that it also works with Clojure 1.7.0 (1.5.1 is at least a year old btw)

**Comment by mjsax** [comment]
Thanks for verifying and reporting this issue!
