### ISSUE TITLE
Cannot use Clojure functions within Flink functions

### ISSUE THREAD

**Issue by lerouxrgd** [mjsax/flink-external#5]
Just change the provided example with:

```clj
(defn my-int []
  (int 1))

(deftype tokenizer [] FlatMapFunction
                     (flatMap [this value collector]
                       (doseq [v (str/split value #"\s")]
                           (.collect collector (Tuple2. v (my-int))))))
```

Then build and run:

```
mvn -DskipTests clean package
flink run target/WordCount-Clojure.jar
```
Results in the following error:

```
org.apache.flink.client.program.ProgramInvocationException: The program execution failed: Job execution failed.
    ...
Caused by: java.lang.IllegalStateException: Attempting to call unbound fn: #'org.apache.flink.clojure.WordCount/my-int
        at clojure.lang.Var$Unbound.throwArity(Var.java:43)
        at clojure.lang.AFn.invoke(AFn.java:28)
        at org.apache.flink.clojure.WordCount.tokenizer.flatMap(WordCount.clj:37)
        at org.apache.flink.runtime.operators.chaining.ChainedFlatMapDriver.collect(ChainedFlatMapDriver.java:80)
        at org.apache.flink.runtime.operators.util.metrics.CountingCollector.collect(CountingCollector.java:35)
        at org.apache.flink.runtime.operators.DataSourceTask.invoke(DataSourceTask.java:168)
        at org.apache.flink.runtime.taskmanager.Task.run(Task.java:718)
        at java.lang.Thread.run(Thread.java:748)
```

So any custom function is seen as an unbound var by Flink. 
Is this an issue with the build logic (aot or something), or is it just impossible to use regular Clojure here ?

**Comment by mjsax** [comment]
This repos was not updated for a long time, and uses a quite old Flink version. I did not check but would assume that the example is not compatible with latest Flink.

**Comment by lerouxrgd** [comment]
Well even with recent Flink versions the original example works. But it is not making use of any user defined function, just clojure.string/split. The point is that with user defined functions it doesn't work anymore.

**Comment by lerouxrgd** [comment]
Actually explicitly requiring the namesapace makes it work:

```clj
(deftype tokenizer [] FlatMapFunction
                     (flatMap [this value collector]
                       (require 'org.apache.flink.clojure.WordCount) ;; With this it works ...
                       (doseq [v (str/split value #"\s")]
                           (.collect collector (Tuple2. v (my-int))))))
```

But it doesn't look like a clean solution to require stuff at the beginning of every function ...

**Comment by lerouxrgd** [comment]
I found a work-around based on macro.
I made a demo repo with it, [check it out](https://github.com/lerouxrgd/squirrel) if you are interested.
